name: Auto Increment Version

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Increment Script Version
        id: versioning
        run: |
          SCRIPT_FILE="mezeze.sh"
          VERSION_LINE=$(grep 'SCRIPT_VERSION=' $SCRIPT_FILE)
          CURRENT_VERSION=$(echo $VERSION_LINE | cut -d '"' -f 2)

          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          ((VERSION_PARTS[2]++))
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"

          sed -i "s/$CURRENT_VERSION/$NEW_VERSION/" $SCRIPT_FILE
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"

      - name: Commit and Push
        if: steps.versioning.outputs.NEW_VERSION != ''
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add mezeze.sh
          git commit -m "Increment script version to ${{ steps.versioning.outputs.NEW_VERSION }}"
          git push

      - name: Create Git Tag
        if: steps.versioning.outputs.NEW_VERSION != ''
        run: |
          git tag v${{ steps.versioning.outputs.NEW_VERSION }}
          git push origin v${{ steps.versioning.outputs.NEW_VERSION }}
