name: Update Contributors List
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        with:
          image_size: 60
          columns_per_row: 6
          commit_message: "Update contributors list"
          readme_path: "README.md"  # Add this if your README is not in the root or has a different name
          use_username: false       # Optional, set to true to use GitHub usernames instead of display names
          auto_detect_branch_protection: true  # Optional
          pr_title_on_protected: 'Update contributors list'  # Optional
          token: ${{ secrets.GITHUB_TOKEN }}  # Authentication token
